# Generated by Django 4.2 on 2023-05-09 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Luchador',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=100)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pais', models.CharField(blank=True, default=0, max_length=50, null=True)),
                ('guardia', models.CharField(max_length=50)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=4)),
                ('alcance', models.DecimalField(decimal_places=2, max_digits=4)),
                ('empates', models.PositiveIntegerField()),
                ('victorias', models.PositiveIntegerField()),
                ('derrotas', models.PositiveIntegerField()),
                ('nacimiento', models.DateField()),
                ('edad', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('golpes_totales', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('golpes_acertados', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('golpes_fallados', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('golpes_recibidos', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('golpes_encajados', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('golpes_evitados', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
