# Generated by Django 4.2 on 2023-05-04 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luchadores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='luchador',
            name='edad',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='luchador',
            name='golpes_acertados',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='luchador',
            name='golpes_encajados',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='luchador',
            name='golpes_evitados',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='luchador',
            name='golpes_fallados',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='luchador',
            name='golpes_recibidos',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='luchador',
            name='golpes_totales',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='luchador',
            name='guardia',
            field=models.CharField(blank=True, default='derecha', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='luchador',
            name='pais',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
