# Generated by Django 4.2 on 2023-05-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luchadores', '0002_alter_luchador_derrotas_alter_luchador_empates_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='luchador',
            old_name='edad',
            new_name='crochets',
        ),
        migrations.AddField(
            model_name='luchador',
            name='directos',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='luchador',
            name='ganchos',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
