# Generated by Django 4.2 on 2023-05-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luchadores', '0003_rename_edad_luchador_crochets_luchador_directos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='luchador',
            name='combates',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
