# Generated by Django 4.2 on 2023-05-05 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('combates', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='combate',
            old_name='boxeador_azul',
            new_name='luchador_azul',
        ),
        migrations.RenameField(
            model_name='combate',
            old_name='boxeador_rojo',
            new_name='luchador_rojo',
        ),
    ]
